# __init__.py
from .soil_moisture_control import monitor_and_control_soil_moisture
from .water_tank_monitor import monitor_and_log_water_tank_level
from .light_control_system import monitor_and_control_light
from .get_humidity_temp import monitor_and_log_temperature_humidity
from .capture import capture_photos_from_webcam
from .telegram_bot import load_telegram
from .user_interface import main